version: '3.8'

services:
  web:
    build: .
    ports:
      - "5001:5001"
    volumes:
      - .:/app
      - sqlite_data:/app/data
    env_file:
      - .env
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
      - FLASK_ENV=development
      - SQLITE_DB_PATH=/app/data/agent_state.db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: '1'
        reservations:
          cpus: '0.25'

  test-agent:
    build: .
    env_file:
      - .env
    command: python tests/test_agent_interactive.py --interactive
    volumes:
      - ./app/agent:/app/agent
      - ./app/config:/app/config
      - ./tests:/app/tests
      - sqlite_data:/app/data
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app
      - SQLITE_DB_PATH=/app/data/agent_state.db

  test-persistence:
    build: .
    env_file:
      - .env
    command: python tests/test_state_persistence.py
    volumes:
      - ./app/agent:/app/agent
      - ./app/config:/app/config
      - ./tests:/app/tests
      - sqlite_data:/app/data
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app
      - SQLITE_DB_PATH=/app/data/agent_state.db

volumes:
  sqlite_data: 