version: '3.8'

services:
  web:
    build: .
    ports:
      - "5001:5001"
    volumes:
      - .:/app
    env_file:
      - .env
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
      - FLASK_ENV=development
      - SQLITE_DB_PATH=/app/data/agent_state.db
      - MONGODB_URI=${MONGODB_URI}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: '1'
        reservations:
          cpus: '0.25'

  test-agent:
    build: .
    env_file:
      - .env
    command: python tests/test_agent_interactive.py --interactive
    volumes:
      - ./app/agent:/app/agent
      - ./app/config:/app/config
      - ./tests:/app/tests
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app
      - SQLITE_DB_PATH=/app/data/agent_state.db
      - MONGODB_URI=${MONGODB_URI}

  test-persistence:
    build: .
    env_file:
      - .env
    command: python tests/test_state_persistence.py
    volumes:
      - ./app/agent:/app/agent
      - ./app/config:/app/config
      - ./tests:/app/tests
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app
      - SQLITE_DB_PATH=/app/data/agent_state.db
      - MONGODB_URI=${MONGODB_URI}

  test-mongodb:
    build: .
    env_file:
      - .env
    command: python tests/test_mongodb_persistence.py
    volumes:
      - ./app/agent:/app/agent
      - ./app/config:/app/config
      - ./tests:/app/tests
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app
      - MONGODB_URI=${MONGODB_URI} 